service: lambda-dynamodb-service

provider:
  name: aws
  runtime: nodejs18.x  # Use the desired Node.js version
  region: ap-southeast-2  # Set the AWS region
  deploymentBucket:
    name: my-custom-deployment-bucket  # Specify your custom bucket name
    serverSideEncryption: AES256  # Optional: Adds encryption for S3 bucket

functions:
  createUser:
    handler: createUser.handler
    events:
      - http:
          path: users
          method: post

  getUser:
    handler: getUser.handler
    events:
      - http:
          path: users
          method: get
          request:
            parameters:
              querystrings:
                userId: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
